name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: SSH deploy using ssh-action
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 98.92.17.79           # your EC2 public IP
          username: ubuntu             # EC2 user
          key: ${{ secrets.EC2_SSH_KEY }}  # your private key secret
          script: |
            cd ~/aws-ec2-docker-nginx-cicd
            git pull
            sudo docker-compose down
            sudo docker-compose up -d --build
