name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key from secrets
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/github_action_key
          chmod 600 ~/.ssh/github_action_key

      # Step 3: SSH into EC2 and deploy
      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_action_key ubuntu@98.92.17.79 << 'EOF'
          cd ~/aws-ec2-docker-nginx-cicd
          git pull
          sudo docker-compose down
          sudo docker-compose up -d --build
          EOF
